name: 'Push docker image'
description: 'Login to docker hub'
inputs:
  server:
    description: 'Image server to logon to'
    required: true
    default: 'https://index.docker.io/v1/'
  username:
    description: 'username to login with'
    required: true
  password:
    description: 'password to login with'
    required: true
  image:
    description: 'Repository of the image'
    required: true
  tag_format:
    description: 'Expected format of the tag'
    required: true
  location:
    description: 'Directory where the image is located'
    required: true
    default: '.'
  dockerfile:
    description: 'Name of the Dockerfile'
    required: true
    default: 'Dockerfile'
runs:
  using: 'node12'
  main: 'dist/index.js'
